name: www.barrymutch.com
favicon: null
layout_spectrum: 0.545730646699667
typography_spectrum: 0.7747472210321575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6131228897720575
  lightness: 0.6478004350792617
  saturation: 0.9419283464085311
  rhythmicContrast: 0.08684569876641035
purpose: []
