typography_spectrum: 0.7450471460649578
content_rating:
  adult: false
color:
  lightness: 0.05482796633496217
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  saturation: 0.6193047166575152
  brandStrength: 0.001021564398698583
  rhythmicContrast: 0.2814975882702425
github: true
opengraph: {}
layout_spectrum: 0.446192039758299
analytics: {}
author:
  name: Barry Mutch
  url: 'http://www.barrymutch.com'
  email: barry@barrymutch.com
name: Barry Mutch
url: 'http://barrymutch.com'
cta:
  bucket: null
  version: null
  domain: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: www.barrymutch.com
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FBk7RVw3I8eg%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DBk7RVw3I8eg&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FBk7RVw3I8eg%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Team Coco
          url: 'https://www.youtube.com/user/teamcoco'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - disturbed
        - the sound of silence
        - simon and garfunkel
        - team coco
        - conan
        - conan o'brien
        - tbs
      description: >-
        Disturbed performs a track from their album Immortalized. More CONAN @
        http://teamcoco.com/video Team Coco is the official YouTube channel of
        late night host Conan O'Brien, CONAN on TBS & TeamCoco.com.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=Bk7RVw3I8eg&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=Bk7RVw3I8eg&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=Bk7RVw3I8eg&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=Bk7RVw3I8eg&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=Bk7RVw3I8eg&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=Bk7RVw3I8eg'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=Bk7RVw3I8eg
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=Bk7RVw3I8eg
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/Bk7RVw3I8eg'
      title: Disturbed "The Sound Of Silence" 03/28/16
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/45693943-404c-4a29-a44e-aa8ea408e6c1.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/45693943-404c-4a29-a44e-aa8ea408e6c1.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: THE HOME OF MUSICIAN - BARRY MUTCH
purpose:
  - type: external
    url: 'http://paypal.me/BarryMutchMusic/13'
    label: >-
      Support The Recording Of Unity - The Album By Pre-Purchasing your digital
      copy today!
