name: Barry Mutch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52104
title: Barry Mutch
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#767676'
    - '#050505'
    - '#505050'
    - '#2d2f2e'
    - '#bcbcbc'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
