name: www.barrymutch.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05192
title: Barry Mutch
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000004'
    - '#e3e3e3'
    - '#9b52bb'
    - '#3f115a'
    - '#868688'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
