name: www.barrymutch.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52671
title: www.barrymutch.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131313'
    - '#fe9792'
    - '#70c9e9'
    - '#3e5773'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
